schema: "1"
pipeline:
  application: pdf
  name: Pdf Cluster Cleanup
  id: phnx-pdf-cleanup
  template:
    source: https://raw.githubusercontent.com/CenterEdge/Phoenix.Spinnaker.PipelineTemplates/master/templates/cluster-cleanup-template.yml
  variables:
    prodclustername: pdf-prod-api
    stagingclustername: pdf-staging-api
    tempclustername: pdf-staging-temp
    imagenamepattern: .*pdf.*
  metadata:
    description: The Pdf Production Cluster Cleanup Config
    name: Pdf-ClusterCleanup
    owner: gbrown@centeredgesoftware.com
    scopes:
    - pdf
configuration:
  inherit: ['concurrentExecutions', 'parameters', 'notifications', 'triggers']