schema: "1"
pipeline:
  application: productcatalogs
  name: ProductCatalogs Production
  id: phnx-productcatalogs-prod
  template:
    source: https://raw.githubusercontent.com/CenterEdge/Phoenix.Spinnaker.PipelineTemplates/master/templates/production-template.yml
  variables:
    application: productcatalogs
    loadbalancer: productcatalogs-prod-api
    clustername: productcatalogs-prod-api
    stagingloadbalancer: productcatalogs-staging-api
    stagingclustername: productcatalogs-staging-api
    imagenamepattern: .*productcatalogs.*
    smoketestjob: Phoenix/job/Services/job/Phoenix.Service.ProductCatalogs/job/Phoenix.Service.ProductCatalogs.Smoke
    gcrrepo: phoenix-177420/phoenix-service-productcatalogs
    gcrimage: us.gcr.io/phoenix-177420/phoenix-service-productcatalogs
  metadata:
    description: The Product Catalogs Production Pipeline Config
    name: ProductCatalogs-Production
    owner: gbaker@centeredgesoftware.com
    scopes:
    - productcatalogs
configuration:
  inherit: ['concurrentExecutions', 'parameters', 'notifications']
  triggers:
  - account: gcr-phoenix
    enabled: true
    organization: phoenix-177420
    registry: us.gcr.io
    repository: phoenix-177420/phoenix-service-productcatalogs
    runAsUser: phoenix-svc-account
    type: docker