schema: "1"
pipeline:
  application: salestax
  name: SalesTax Production
  id: phnx-salestax-prod
  template:
    source: https://raw.githubusercontent.com/CenterEdge/Phoenix.Spinnaker.PipelineTemplates/master/templates/production-template.yml
  variables:
    application: salestax
    loadbalancer: salestax-prod-api
    clustername: salestax-prod-api
    stagingloadbalancer: salestax-staging-api
    stagingclustername: salestax-staging-api
    imagenamepattern: .*salestax.*
    smoketestjob: Phoenix/job/Services/job/Phoenix.Service.SalesTax/job/Phoenix.Service.SalesTax.Smoke
    gcrrepo: phoenix-177420/phoenix-service-salestax
    gcrimage: us.gcr.io/phoenix-177420/phoenix-service-salestax
    podAnnotations: "{ environment: prod }"
    podAnnotationsStaging: "{ environment: staging }"
  metadata:
    description: The SalesTax Production Pipeline Config
    name: SalesTax-Production
    owner: gbaker@centeredgesoftware.com
    scopes:
    - salestax
configuration:
  inherit: ['concurrentExecutions', 'parameters', 'notifications']
  triggers:
  - account: gcr-phoenix
    enabled: true
    organization: phoenix-177420
    registry: us.gcr.io
    repository: phoenix-177420/phoenix-service-salestax
    runAsUser: phoenix-svc-account
    type: docker