schema: "1"
pipeline:
  application: customers
  name: Temp Smoke Test
  id: phoenix-customers-tempsmoketest
  template:
    source: https://raw.githubusercontent.com/CenterEdge/Phoenix.Spinnaker.PipelineTemplates/master/templates/tempsmoketest-template.yml
  variables:
    application: customers
    loadbalancer: customers-staging-api
    clustername: customers-staging-temp
    gcrrepo: phoenix-177420/phoenix-service-customers
    gcrimage: us.gcr.io/phoenix-177420/phoenix-service-customers:latest
    podAnnotations: "{ environment: staging }"
  metadata:
    description: A Temporary Smoke Test Configuration
    name: Customers-TempSmokeTest
    owner: gbaker@centeredgesoftware.com
    scopes:
    - customers
configuration:
  inherit: ['concurrentExecutions', 'parameters', 'notifications']
  triggers: []