id: phnx-staging-v4
lastModifiedBy: bburnett@centeredgesoftware.com
metadata:
  description: Creates a staging pipeline
  name: Kustomize V4 Phoenix Service Staging
  scopes:
  - global
pipeline:
  expectedArtifacts:
  - defaultArtifact:
      customKind: true
      id: 39b0955b-01fc-4001-aa27-9dfa7074937a
    displayName: ${ templateVariables.appName }
    id: 0f5786e8-3a1e-4dc3-a038-3d31bf6c1366
    matchArtifact:
      artifactAccount: docker-registry
      name: "us.gcr.io/${ templateVariables.gcrAccountName }/${ templateVariables.gcrImageName == '*' ? 'phoenix-service-' + templateVariables.appName : templateVariables.gcrImageName }"
      type: docker/image
    useDefaultArtifact: false
    usePriorArtifact: false
  - defaultArtifact:
      customKind: true
      id: abaeac64-c6c6-47b5-962a-691bcb6d31bd
    displayName: github-repo
    id: 90161e9a-4aae-4bed-83e1-c924b7e8eb6a
    matchArtifact:
      artifactAccount: github
      name: github-repo
      reference: ${templateVariables.gitHubRepo }
      type: git/repo
  keepWaitingPipelines: false
  limitConcurrent: true
  stages:
  - expectedArtifacts:
    - defaultArtifact:
        customKind: true
        id: 31f8d68f-a95d-488d-b573-91b1da295d4f
      displayName: manifest-staging
      id: 8877348a-0a3d-4243-98f3-9fc670558ad7
      matchArtifact:
        artifactAccount: embedded-artifact
        customKind: false
        id: b8a47e06-8453-4282-8151-1e3c55b53689
        name: manifest-staging
        type: embedded/base64
      useDefaultArtifact: false
      usePriorArtifact: false
    inputArtifact:
      id: 90161e9a-4aae-4bed-83e1-c924b7e8eb6a
    kustomizeFilePath: deployment/env/staging/kustomization.yaml
    name: Bake (Staging)
    overrides: {}
    refId: "3"
    requisiteStageRefIds: []
    templateRenderer: KUSTOMIZE
    type: bakeManifest
  - account: phoenix-v2
    cloudProvider: kubernetes
    manifestArtifactId: 8877348a-0a3d-4243-98f3-9fc670558ad7
    moniker:
      app: ${ templateVariables.appName }
    name: Deploy (Staging)
    namespaceOverride: default
    refId: "4"
    requiredArtifactIds:
    - 0f5786e8-3a1e-4dc3-a038-3d31bf6c1366
    requisiteStageRefIds:
    - "3"
    skipExpressionEvaluation: false
    source: artifact
    trafficManagement:
      enabled: false
      options:
        enableTraffic: false
        services: []
    type: deployManifest
  triggers: []
protect: false
schema: v2
variables:
- defaultValue: ""
  description: Application Name
  name: appName
  type: string
- defaultValue: phoenix-177420
  description: The GCR account name that contains the image
  name: gcrAccountName
  type: string
- defaultValue: '*'
  description: "The image name to pull; leave '*' to use default pattern: phoenix-service-{appName}"
  name: gcrImageName
  type: string
- defaultValue: ''
  description: "GitHub repository path (should end in '.git')"
  name: gitHubRepo
  type: string
