schema: "1"
pipeline:
  application: businessentities
  name: BusinessEntities Cluster Cleanup
  id: phnx-businessentities-cleanup
  template:
    source: https://raw.githubusercontent.com/CenterEdge/Phoenix.Spinnaker.PipelineTemplates/master/templates/cluster-cleanup-template.yml
  variables:
    prodclustername: businessentities-prod-api
    stagingclustername: businessentities-staging-api
    tempclustername: businessentities-staging-temp
    imagenamepattern: .*businessentities.*
  metadata:
    description: The Business Entities Production Cluster Cleanup Config
    name: BusinessEntities-ClusterCleanup
    owner: gbaker@centeredgesoftware.com
    scopes:
    - businessentities
configuration:
  inherit: ['concurrentExecutions', 'parameters', 'notifications', 'triggers']