schema: "1"
pipeline:
  application: transactions
  name: Transactions Production
  id: phnx-transactions-prod
  template:
    source: https://raw.githubusercontent.com/CenterEdge/Phoenix.Spinnaker.PipelineTemplates/master/templates/production-template.yml
  variables:
    application: transactions
    loadbalancer: transactions-prod-api
    clustername: transactions-prod-api
    stagingloadbalancer: transactions-staging-api
    stagingclustername: transactions-staging-api
    imagenamepattern: .*transactions.*
    smoketestjob: Phoenix/job/Services/job/Phoenix.Service.Transactions/job/Phoenix.Service.Transactions.Smoke
    gcrrepo: phoenix-177420/phoenix-service-transactions
    gcrimage: us.gcr.io/phoenix-177420/phoenix-service-transactions
    podAnnotations: "{ environment: prod }"
    podAnnotationsStaging: "{ environment: staging }"
    shawarmaEnabled: true
  metadata:
    description: The Transactions Production Pipeline Config
    name: Transactions-Production
    owner: gbaker@centeredgesoftware.com
    scopes:
    - transactions
configuration:
  inherit: ['concurrentExecutions', 'parameters', 'notifications']
  triggers:
  - account: gcr-phoenix
    enabled: true
    organization: phoenix-177420
    registry: us.gcr.io
    repository: phoenix-177420/phoenix-service-transactions
    runAsUser: phoenix-svc-account
    type: docker