schema: "1"
pipeline:
  application: waivers
  name: Emergency Waivers Production
  id: phnx-emergency-waivers-prod
  template:
    source: https://raw.githubusercontent.com/CenterEdge/Phoenix.Spinnaker.PipelineTemplates/master/templates/emergency-production-template.yml
  variables:
    application: waivers
    loadbalancer: waivers-prod-api
    clustername: waivers-prod-api
    jobsloadbalancer: waivers-prod-jobs
    jobsclustername: waivers-jobs-api
    gcrrepo: phoenix-177420/phoenix-service-waivers
    gcrimage: us.gcr.io/phoenix-177420/phoenix-service-waivers
    podAnnotations: "{ iam.amazonaws.com/role: PhoenixWaiversSvc, environment: prod }"
    podAnnotationsProdJobs: "{ iam.amazonaws.com/role: PhoenixWaiversSvc, environment: prod }"
    maxmem: 4096Mi
    shawarmaEnabled: true
  metadata:
    description: The Emergency Waivers Production Pipeline Config
    name: Emergency Waivers-Production
    owner: gbrown@centeredgesoftware.com
    scopes:
    - waivers
configuration:
  inherit: ['concurrentExecutions', 'parameters', 'notifications']
  triggers:
  - account: gcr-phoenix
    enabled: false
    organization: phoenix-177420
    registry: us.gcr.io
    repository: phoenix-177420/phoenix-service-waivers
    runAsUser: phoenix-svc-account
    type: docker
stages:
- config:
    clusters:
    - account: phoenix
      application: "{{ application }}"
      capacity:
        desired: 2
        max: 9
        min: 2
      cloudProvider: kubernetes
      containers:
      - args: []
        command: []
        envVars:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: Statsd__Config__StatsdServerName
          envSource:
            fieldRef:
              fieldPath: status.hostIP
        - name: Statsd__Enabled
          value: "true"
        - envSource:
            configMapSource:
              configMapName: businessentities-api
              key: url
          name: BusinessEntities__Host
        - envSource:
            configMapSource:
              configMapName: mappings-api
              key: url
          name: Mappings__Host
        - envSource:
            configMapSource:
              configMapName: productcatalogs-api
              key: url
          name: ProductCatalogs__Host
        - envSource:
            configMapSource:
              configMapName: pdf-api
              key: url
          name: HtmlToPdf__Host
        - envSource:
            secretSource:
              key: connectionString
              secretName: couchbase-primary
          name: Couchbase__ConnectionString
        - envSource:
            secretSource:
              key: username
              secretName: couchbase-primary
          name: Couchbase__Username
        - envSource:
            secretSource:
              key: password
              secretName: couchbase-primary
          name: Couchbase__Password
        - name: ASPNETCORE_URLS
          value: http://localhost:8080/
        - envSource:
            configMapSource:
              configMapName: rabbitmq
              key: host
          name: RabbitMQ__Hosts__0__Host
        - envSource:
            configMapSource:
              configMapName: rabbitmq
              key: username
          name: RabbitMQ__Username
        - envSource:
            secretSource:
              key: default-pass
              secretName: rabbitmq-config
          name: RabbitMQ__Password
        - envSource:
            secretSource:
              key: key
              secretName: feature-flag-key
          name: LaunchDarklyOptions__SdkKey
        - envSource:
            configMapSource:
              configMapName: timeouts
              key: keepalive
          name: TimeoutOptions__KeepAliveTimeout
        - envSource:
            configMapSource:
              configMapName: timeouts
              key: keepalive
          name: WaiverUploadOptions__KeepAliveTimeout
        - name: JobOptions__ProcessBulkJobs
          value: true
        imageDescription:
          account: gcr-phoenix
          fromTrigger: true
          imageId: "{{ gcrimage }}"
          registry: us.gcr.io
          repository: "{{ gcrrepo }}"
        imagePullPolicy: IFNOTPRESENT
        limits:
          cpu: "{{ maxcpu }}"
          memory: "{{ maxmem }}"
        livenessProbe:
          failureThreshold: 3
          handler:
            execAction:
              commands: []
            httpGetAction:
              path: /health
              port: 80
              uriScheme: HTTP
            tcpSocketAction:
              port: 80
            type: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: "phoenix-{{ application }}-image"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          handler:
            execAction:
              commands: []
            httpGetAction:
              path: /health?type=ready
              port: 80
              uriScheme: HTTP
            tcpSocketAction:
              port: 80
            type: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        requests:
          cpu: "{{ requestcpu }}"
          memory: "{{ requestmem }}"
        volumeMounts: []
      - args: []
        command: []
        envVars:
        - name: STATSD_SERVER
          envSource:
            fieldRef:
              fieldPath: status.hostIP
        - name: STATSD_SAMPLE_RATE
          value: "{{ statsdSampleRate }}"
        - name: SERVICE_NAME
          value: "prod.{{ application }}"
        - envSource:
            configMapSource:
              configMapName: timeouts
              key: connect_read_write
          name: TimeoutOptions__ConnectTimeout
        - envSource:
            configMapSource:
              configMapName: timeouts
              key: connect_read_write
          name: TimeoutOptions__ReadTimeout
        - envSource:
            configMapSource:
              configMapName: timeouts
              key: connect_read_write
          name: TimeoutOptions__SendTimeout
        - envSource:
            configMapSource:
              configMapName: waiver-upload-options
              key: max_size
          name: WaiverUploadOptions__MaxRequestSize
        imageDescription:
          account: gcr-phoenix
          imageId: us.gcr.io/phoenix-177420/nginx-proxy:27
          registry: us.gcr.io
          repository: phoenix-177420/nginx-proxy
          tag: "27"
        imagePullPolicy: IFNOTPRESENT
        limits:
          cpu: "{{ maxcpu }}"
          memory: "{{ maxmem }}"
        name: phoenix-177420-nginx-proxy
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        requests:
          cpu: "{{ requestcpu }}"
          memory: "{{ requestmem }}"
        volumeMounts: []
      deployment:
        deploymentStrategy:
          rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
          type: RollingUpdate
        enabled: false
        minReadySeconds: 0
      dnsPolicy: ClusterFirst
      freeFormDetails: api
      interestingHealthProviderNames:
      - KubernetesContainer
      - KubernetesPod
      loadBalancers:
      - "{{ jobsloadbalancer }}"
      namespace: default
      nodeSelector: {}
      podAnnotations: |
        {% if not shawarmaEnabled -%}
        {{ podAnnotationsProdJobs }}
        {% elif podAnnotationsProdJobs == '{}' -%}
        {"shawarma.centeredge.io/service-name": "{{ jobsloadbalancer }}"}
        {% else -%}
        {{ podAnnotationsProdJobs.substring(0, podAnnotationsProdJobs.length()-1) }}, "shawarma.centeredge.io/service-name": "{{ jobsloadbalancer }}"}
        {%- endif %}
      provider: kubernetes
      region: default
      replicaSetAnnotations: {}
      scalingPolicy:
        cpuUtilization:
          target: 40
      stack: jobs
      strategy: ""
      targetSize: 3
      terminationGracePeriodSeconds: 30
      volumeSources: []
    overrideTimeout: true
    stageTimeoutMs: 600000
    stageEnabled:
      expression: "#judgment('Manual Judgment').equals('Approve')"
      type: expression
  id: phoenix-production-jobs-deploy
  inheritanceControl: {}
  dependsOn:
  - phoenix-production-manualjudgment
  inject: {}
  name: Deploy Production Jobs
  type: deploy
- config:
    cloudProvider: kubernetes
    cloudProviderType: kubernetes
    cluster: "{{ jobsclustername }}"
    credentials: phoenix
    interestingHealthProviderNames:
    - KubernetesService
    namespaces:
    - default
    preferLargerOverNewer: "false"
    remainingEnabledServerGroups: 1
  dependsOn:
  - phoenix-production-jobs-deploy
  id: phoenix-production-jobs-disablecluster
  inheritanceControl: {}
  inject: {}
  name: Disable Cluster
  type: disableCluster
- config:
    allowDeleteActive: false
    cloudProvider: kubernetes
    cloudProviderType: kubernetes
    cluster: "{{ jobsclustername }}"
    credentials: phoenix
    namespaces:
    - default
    retainLargerOverNewer: "false"
    shrinkToSize: 2
  dependsOn:
  - phoenix-production-jobs-disablecluster
  id: phoenix-production-jobs-shrinkcluster
  inheritanceControl: {}
  inject: {}
  name: Shrink Cluster
  type: shrinkCluster
